stages:
  - clippy
  - build
  - deploy

clippy:
  stage: clippy
  image: nixos/nix
  tags:
    - amd64
  script:
    - nix develop --extra-experimental-features 'nix-command flakes' --command bash -c 'cargo clippy -- -D warnings'

build-wasm-job:
  stage: build
  image: nixos/nix
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - res
  tags:
    - amd64
  script:
    - "nix --extra-experimental-features 'nix-command flakes' build ."
    - "mkdir res && cp -r /nix/store/*-trunk-template*/* res"

pages:
  stage: deploy
  dependencies:
  - build-wasm-job
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - public/*
  tags:
    - amd64
  script:
    - "mv res/dist public"
